display server log  Build: v1.3

diff --git a/.github/workflows/back_build_teset.yaml b/.github/workflows/back_build_teset.yaml
--- a/.github/workflows/back_build_teset.yaml
+++ b/.github/workflows/back_build_teset.yaml
@@ -57,9 +57,15 @@ jobs:
         run: |
           nohup yarn dev > server.log 2>&1 &
           echo "Development server started in the background"
-          sleep 10 
+          sleep 30 
         working-directory: 'backend'
 
       - name: Display server logs
         run: |
-          tail -n 100 server.log 
+          if [ -f $GITHUB_WORKSPACE/server.log ]; then
+            echo "server.log contents:"
+            tail -n 100 $GITHUB_WORKSPACE/server.log
+          else
+            echo "server.log not found!"
+            exit 1
+          fi
